linter:
  rules:
    require_trailing_commas: true 
    prefer_relative_imports: true 
    always_declare_return_types: true 
    always_require_non_null_named_parameters: true 
    annotate_overrides: true 
    avoid_empty_else: true 
    avoid_slow_async_io: true 
    avoid_types_as_parameter_names: true 
    avoid_unused_constructor_parameters: true 
    await_only_futures: true 
    avoid_returning_null: true 
    avoid_unnecessary_containers: true 
    camel_case_types: true 
    camel_case_extensions: true 
    cancel_subscriptions: true 
    directives_ordering: true 
    empty_constructor_bodies: true 
    file_names: true
    library_names: true 
    library_prefixes: true 
    list_remove_unrelated_type: true 
    no_duplicate_case_values: true 
    non_constant_identifier_names: true 
    prefer_asserts_in_initializer_lists: true 
    prefer_collection_literals: true 
    prefer_conditional_assignment: true 
    prefer_const_constructors: true 
    prefer_const_declarations: true 
    prefer_contains: true 
    prefer_equal_for_default_values: true 
    prefer_final_fields: true 
    prefer_foreach: false 
    prefer_initializing_formals: true 
    prefer_if_elements_to_conditional_expressions: true 
    prefer_interpolation_to_compose_strings: true 
    prefer_is_empty: true 
    prefer_is_not_empty: true 
    prefer_iterable_whereType: true 
    prefer_single_quotes: true 
    prefer_void_to_null: true 
    recursive_getters: true
    unnecessary_brace_in_string_interps: true 
    unnecessary_const: true 
    unnecessary_new: true 
    unnecessary_null_aware_assignments: true 
    unnecessary_null_in_if_null_operators: true 
    unnecessary_overrides: true 
    unnecessary_parenthesis: true 
    unnecessary_statements: true 
    unnecessary_this: true 
    unnecessary_raw_strings: true 
    valid_regexps: true 
    package_names: true 
    use_rethrow_when_possible: true 
    avoid_void_async: true